language: java
services:
  - mysql
before_script:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS InstaTicketApi;'
  - mysql -u root -e "CREATE USER 'isa'@'localhost' IDENTIFIED BY 'isa';"
  - mysql -u root -e "GRANT ALL ON InstaTicketApi.* TO 'isa'@'localhost';"
