# Use root/example as user/password credentials
version: '3.1'

services:
  # This is Main App REST API
  api:
    build: .
    container_name: instanticket-api
    restart: always
    ports:
      - "8090:8090"

  # MySQL Database container
  db-spring:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: InstaTicketApi
      TZ:
    ports:
      - 3306:3306
    volumes:
      - mysqlspringdatavolume:/var/lib/mysql

# Volume for MySQL data so we keep data persistent
volumes:
  mysqlspringdatavolume: