spring:
    application:
        name: InstaticketapiApplication
    profiles:
        active:

security:
    basic:
        enabled: false

server:
    session:
        cookie:
            http-only: true

info:
    project:
        version: version 1.0

management:
    security:
        roles: ADMIN
    context-path: /management
    info:
        git:
            mode: full
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true

application:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    mail:
        from: Instaticketapi@localhost
    swagger:
        default-include-pattern: /api/.*
        title: InstaTicket API
        description: InstaTicket API documentation
        version: 1.0
        terms-of-service-url:
        contact-name: Nemanja Mudrinic
        contact-url:
        contact-email: mudrinic.nemanja@itengine.co.rs
        license:
        license-url:
    ribbon:
        display-on-active-profiles: dev